org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

mod_version=0.4.0
maven_group=com.ice2974
archives_base_name=carpet-ice-addition
mod_id=carpet-ice-addition
mod_name=Carpet Ice Addition

loader_version=0.18.4

mc1211_minecraft_version=1.21.1
mc1211_release_minecraft_range=1.21~1.21.1
mc1211_minecraft_dependency=>=1.21 <=1.21.1
mc1211_yarn_mappings=1.21.1+build.3
mc1211_fabric_version=0.102.1+1.21.1
mc1211_fabric_dependency=0.102.0+1.21
mc1211_carpet_version=1.21-1.4.147+v240613
mc1211_carpet_dependency=1.4.147

mc1218_minecraft_version=1.21.8
mc1218_release_minecraft_range=1.21.7~1.21.8
mc1218_minecraft_dependency=>=1.21.7 <=1.21.8
mc1218_yarn_mappings=1.21.8+build.1
mc1218_fabric_version=0.133.4+1.21.8
mc1218_fabric_dependency=0.129.0+1.21.7
mc1218_carpet_version=1.21.7-1.4.177+v250630
mc1218_carpet_dependency=1.4.177
