pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'carpet-ice-addition'
include 'common'
include 'versions:platform-mc1211'
include 'versions:platform-mc1213'
include 'versions:platform-mc1214'
include 'versions:platform-mc1215'
include 'versions:platform-mc1216'
include 'versions:platform-mc1218'
include 'versions:platform-mc1219'
include 'versions:platform-mc12110'

project(':versions:platform-mc1211').projectDir = file('versions/platform-mc1211')
project(':versions:platform-mc1213').projectDir = file('versions/platform-mc1213')
project(':versions:platform-mc1214').projectDir = file('versions/platform-mc1214')
project(':versions:platform-mc1215').projectDir = file('versions/platform-mc1215')
project(':versions:platform-mc1216').projectDir = file('versions/platform-mc1216')
project(':versions:platform-mc1218').projectDir = file('versions/platform-mc1218')
project(':versions:platform-mc1219').projectDir = file('versions/platform-mc1219')
project(':versions:platform-mc12110').projectDir = file('versions/platform-mc12110')
